export enum TableColumn {
  position = 'position',
  assignment_name = 'name',
  assignment_due_datetime = 'dueDatetime',
  assignment_student = 'Student\'s Name',
  assignment_status = 'Submission Status',
  assignment_feedback_datetime = 'Feedback Status',
  assignment_instructor = 'Instructor',
  assignment_school = 'school',
  assignment_group = 'group',
  freelancer_username = 'Freelancer\'s Name',
  freelancer_school = 'Schools',
  freelancer_group = 'Groups',
  wage_created_datetime = 'Month/Year',
  wage_hours = 'Hours',
  account_role = 'Role',
  account_username = 'Username',
  account_school = 'School',
  account_group = 'Group',
  account_created_datetime = 'Created Date',
  actions = 'actions'
}
