export enum TableColumn {
  position = 'position',
  assignment_name = 'name',
  assignment_name2 = 'assignment_name',
  assignment_submission_assignment_name = 'assignment.name',
  assignment_due_datetime = 'dueDatetime',
  assignment_submission_due_datetime = 'assignment.dueDatetime',
  assignment_student_name = 'student_name',
  assignment_submission_submission_status = 'assignment.submitted_datetime',
  assignment_submission_status = 'submitted_datetime',
  assignment_feedback_datetime = 'feedback_datetime',
  assignment_instructor = 'instructor_name',
  assignment_school = 'school',
  assignment_group = 'group',
  freelancer_username = 'Freelancer\'s Name',
  freelancer_school = 'Schools',
  freelancer_group = 'Groups',
  wage_created_datetime = 'Month/Year',
  wage_hours = 'Hours',
  account_role = 'role',
  account_username = 'username',
  account_school = 'school',
  account_group = 'group',
  account_created_datetime = 'created_datetime',
  actions = 'actions'
}
